// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkiKqON8XBBQkGB2nhFEkMyom6c_Hop5I',
    appId: '1:620545516658:web:d31ffd62fc43d11b0c8eeb',
    messagingSenderId: '620545516658',
    projectId: 'studify-31a6d',
    authDomain: 'studify-31a6d.firebaseapp.com',
    databaseURL: 'https://studify-31a6d-default-rtdb.firebaseio.com',
    storageBucket: 'studify-31a6d.appspot.com',
    measurementId: 'G-53EEJDZ8M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoNn3SYxZdvl8b7aq1wAkLCCAe_SPNcWA',
    appId: '1:620545516658:android:87ad1a92dc4bbf510c8eeb',
    messagingSenderId: '620545516658',
    projectId: 'studify-31a6d',
    databaseURL: 'https://studify-31a6d-default-rtdb.firebaseio.com',
    storageBucket: 'studify-31a6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSa_oD579_xIi1qKpVQGaGuIGj9xpxRJM',
    appId: '1:620545516658:ios:b6b27ffebd1ab9580c8eeb',
    messagingSenderId: '620545516658',
    projectId: 'studify-31a6d',
    databaseURL: 'https://studify-31a6d-default-rtdb.firebaseio.com',
    storageBucket: 'studify-31a6d.appspot.com',
    iosClientId: '620545516658-gk012j2gjc2mnc4m0im0urrbrcceiluq.apps.googleusercontent.com',
    iosBundleId: 'com.skeletonpythons.studify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkiKqON8XBBQkGB2nhFEkMyom6c_Hop5I',
    appId: '1:620545516658:web:cf5c28987834ff520c8eeb',
    messagingSenderId: '620545516658',
    projectId: 'studify-31a6d',
    authDomain: 'studify-31a6d.firebaseapp.com',
    databaseURL: 'https://studify-31a6d-default-rtdb.firebaseio.com',
    storageBucket: 'studify-31a6d.appspot.com',
    measurementId: 'G-TTVTD1ESX7',
  );
}
