import '../models/flashcard_model.dart';

List<Note> sample = [
  Note(
    title: 'Note 1',
    content: 'This is the content of note 1',
    front: 'What is the capital of Alabama?',
    back: 'Montgomery',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 2',
    content: 'This is the content of note 2',
    front: 'What is the capital of Alaska?',
    back: 'Juneau',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 3',
    content: 'This is the content of note 3',
    front: 'What is the capital of Arizona?',
    back: 'Phoenix',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 4',
    content: 'This is the content of note 4',
    front: 'What is the capital of Arkansas?',
    back: 'Little Rock',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 5',
    content: 'This is the content of note 5',
    front: 'What is the capital of California?',
    back: 'Sacramento',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 6',
    content: 'This is the content of note 6',
    front: 'What is the capital of Colorado?',
    back: 'Denver',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 7',
    content: 'This is the content of note 7',
    front: 'What is the capital of Connecticut?',
    back: 'Hartford',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 8',
    content: 'This is the content of note 8',
    front: 'What is the capital of Delaware?',
    back: 'Dover',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 9',
    content: 'This is the content of note 9',
    front: 'What is the capital of Florida?',
    back: 'Tallahassee',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 10',
    content: 'This is the content of note 10',
    front: 'What is the capital of Georgia?',
    back: 'Atlanta',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 11',
    content: 'This is the content of note 11',
    front: 'What is the capital of Hawaii?',
    back: 'Honolulu',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 12',
    content: 'This is the content of note 12',
    front: 'What is the capital of Idaho?',
    back: 'Boise',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 13',
    content: 'This is the content of note 13',
    front: 'What is the capital of Illinois?',
    back: 'Springfield',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 14',
    content: 'This is the content of note 14',
    front: 'What is the capital of Indiana?',
    back: 'Indianapolis',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 15',
    content: 'This is the content of note 15',
    front: 'What is the capital of Iowa?',
    back: 'Des Moines',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 16',
    content: 'This is the content of note 16',
    front: 'What is the capital of Kansas?',
    back: 'Topeka',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 17',
    content: 'This is the content of note 17',
    front: 'What is the capital of Kentucky?',
    back: 'Frankfort',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 18',
    content: 'This is the content of note 18',
    front: 'What is the capital of Louisiana?',
    back: 'Baton Rouge',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 19',
    content: 'This is the content of note 19',
    front: 'What is the capital of Maine?',
    back: 'Augusta',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
];
