import '../models/flashcard_model.dart';

List<Note> sample = [
  Note(
    title: 'Note 1',
    content: 'This is the content of note 1',
    front: 'What is the capital of Alabama?',
    back: 'Montgomery',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 2',
    content: 'This is the content of note 2',
    front: 'What is the capital of Alaska?',
    back: 'Juneau',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 3',
    content: 'This is the content of note 3',
    front: 'What is the capital of Arizona?',
    back: 'Phoenix',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 4',
    content: 'This is the content of note 4',
    front: 'What is the capital of Arkansas?',
    back: 'Little Rock',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 5',
    content: 'This is the content of note 5',
    front: 'What is the capital of California?',
    back: 'Sacramento',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 6',
    content: 'This is the content of note 6',
    front: 'What is the capital of Colorado?',
    back: 'Denver',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 7',
    content: 'This is the content of note 7',
    front: 'What is the capital of Connecticut?',
    back: 'Hartford',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 8',
    content: 'This is the content of note 8',
    front: 'What is the capital of Delaware?',
    back: 'Dover',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 9',
    content: 'This is the content of note 9',
    front: 'What is the capital of Florida?',
    back: 'Tallahassee',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 10',
    content: 'This is the content of note 10',
    front: 'What is the capital of Georgia?',
    back: 'Atlanta',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 11',
    content: 'This is the content of note 11',
    front: 'What is the capital of Hawaii?',
    back: 'Honolulu',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 12',
    content: 'This is the content of note 12',
    front: 'What is the capital of Idaho?',
    back: 'Boise',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 13',
    content: 'This is the content of note 13',
    front: 'What is the capital of Illinois?',
    back: 'Springfield',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 14',
    content: 'This is the content of note 14',
    front: 'What is the capital of Indiana?',
    back: 'Indianapolis',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 15',
    content: 'This is the content of note 15',
    front: 'What is the capital of Iowa?',
    back: 'Des Moines',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 16',
    content: 'This is the content of note 16',
    front: 'What is the capital of Kansas?',
    back: 'Topeka',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 17',
    content: 'This is the content of note 17',
    front: 'What is the capital of Kentucky?',
    back: 'Frankfort',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 18',
    content: 'This is the content of note 18',
    front: 'What is the capital of Louisiana?',
    back: 'Baton Rouge',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 19',
    content: 'This is the content of note 19',
    front: 'What is the capital of Maine?',
    back: 'Augusta',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 20',
    content: 'This is the content of note 20',
    front: 'What is the capital of Maryland?',
    back: 'Annapolis',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 21',
    content: 'This is the content of note 21',
    front: 'What is the capital of Massachusetts?',
    back: 'Boston',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 22',
    content: 'This is the content of note 22',
    front: 'What is the capital of Michigan?',
    back: 'Lansing',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 23',
    content: 'This is the content of note 23',
    front: 'What is the capital of Minnesota?',
    back: 'St. Paul',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 24',
    content: 'This is the content of note 24',
    front: 'What is the capital of Mississippi?',
    back: 'Jackson',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 25',
    content: 'This is the content of note 25',
    front: 'What is the capital of Missouri?',
    back: 'Jefferson City',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 26',
    content: 'This is the content of note 26',
    front: 'What is the capital of Montana?',
    back: 'Helena',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 27',
    content: 'This is the content of note 27',
    front: 'What is the capital of Nebraska?',
    back: 'Lincoln',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 28',
    content: 'This is the content of note 28',
    front: 'What is the capital of Nevada?',
    back: 'Carson City',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 29',
    content: 'This is the content of note 29',
    front: 'What is the capital of New Hampshire?',
    back: 'Concord',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 30',
    content: 'This is the content of note 30',
    front: 'What is the capital of New Jersey?',
    back: 'Trenton',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 31',
    content: 'This is the content of note 31',
    front: 'What is the capital of New Mexico?',
    back: 'Santa Fe',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 32',
    content: 'This is the content of note 32',
    front: 'What is the capital of New York?',
    back: 'Albany',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 33',
    content: 'This is the content of note 33',
    front: 'What is the capital of North Carolina?',
    back: 'Raleigh',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 34',
    content: 'This is the content of note 34',
    front: 'What is the capital of North Dakota?',
    back: 'Bismarck',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 35',
    content: 'This is the content of note 35',
    front: 'What is the capital of Ohio?',
    back: 'Columbus',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 36',
    content: 'This is the content of note 36',
    front: 'What is the capital of Oklahoma?',
    back: 'Oklahoma City',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 37',
    content: 'This is the content of note 37',
    front: 'What is the capital of Oregon?',
    back: 'Salem',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 38',
    content: 'This is the content of note 38',
    front: 'What is the capital of Pennsylvania?',
    back: 'Harrisburg',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 39',
    content: 'This is the content of note 39',
    front: 'What is the capital of Rhode Island?',
    back: 'Providence',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 40',
    content: 'This is the content of note 40',
    front: 'What is the capital of South Carolina?',
    back: 'Columbia',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 41',
    content: 'This is the content of note 41',
    front: 'What is the capital of South Dakota?',
    back: 'Pierre',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 42',
    content: 'This is the content of note 42',
    front: 'What is the capital of Tennessee?',
    back: 'Nashville',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 43',
    content: 'This is the content of note 43',
    front: 'What is the capital of Texas?',
    back: 'Austin',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 44',
    content: 'This is the content of note 44',
    front: 'What is the capital of Utah?',
    back: 'Salt Lake City',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 45',
    content: 'This is the content of note 45',
    front: 'What is the capital of Vermont?',
    back: 'Montpelier',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 46',
    content: 'This is the content of note 46',
    front: 'What is the capital of Washington?',
    back: 'Seattle',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 47',
    content: 'This is the content of note 47',
    front: 'What is the capital of West Virginia?',
    back: 'Charleston',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 48',
    content: 'This is the content of note 48',
    front: 'What is the capital of Wisconsin?',
    back: 'Madison',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
  Note(
    title: 'Note 49',
    content: 'This is the content of note 49',
    front: 'What is the capital of Wyoming?',
    back: 'Cheyenne',
    isLearned: false,
    tags: ['states', 'capitals'],
    isFav: false,
    isPinned: false,
  ),
];
