import '../models/flashcard_model.dart';

List<Note> sample = [
  Note(
    subject: 'Geography',
    content: 'This is the content of note 1',
    front: 'What is the capital of Alabama?',
    back: 'Montgomery',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 2',
    front: 'What is the capital of Alaska?',
    back: 'Juneau',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 3',
    front: 'What is the capital of Arizona?',
    back: 'Phoenix',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 4',
    front: 'What is the capital of Arkansas?',
    back: 'Little Rock',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 5',
    front: 'What is the capital of California?',
    back: 'Sacramento',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 6',
    front: 'What is the capital of Colorado?',
    back: 'Denver',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 7',
    front: 'What is the capital of Connecticut?',
    back: 'Hartford',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 8',
    front: 'What is the capital of Delaware?',
    back: 'Dover',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 9',
    front: 'What is the capital of Florida?',
    back: 'Tallahassee',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 10',
    front: 'What is the capital of Georgia?',
    back: 'Atlanta',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 11',
    front: 'What is the capital of Hawaii?',
    back: 'Honolulu',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 12',
    front: 'What is the capital of Idaho?',
    back: 'Boise',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 13',
    front: 'What is the capital of Illinois?',
    back: 'Springfield',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 14',
    front: 'What is the capital of Indiana?',
    back: 'Indianapolis',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 15',
    front: 'What is the capital of Iowa?',
    back: 'Des Moines',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 16',
    front: 'What is the capital of Kansas?',
    back: 'Topeka',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 17',
    front: 'What is the capital of Kentucky?',
    back: 'Frankfort',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 18',
    front: 'What is the capital of Louisiana?',
    back: 'Baton Rouge',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 19',
    front: 'What is the capital of Maine?',
    back: 'Augusta',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 20',
    front: 'What is the capital of Maryland?',
    back: 'Annapolis',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 21',
    front: 'What is the capital of Massachusetts?',
    back: 'Boston',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 22',
    front: 'What is the capital of Michigan?',
    back: 'Lansing',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 23',
    front: 'What is the capital of Minnesota?',
    back: 'St. Paul',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 24',
    front: 'What is the capital of Mississippi?',
    back: 'Jackson',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 25',
    front: 'What is the capital of Missouri?',
    back: 'Jefferson City',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 26',
    front: 'What is the capital of Montana?',
    back: 'Helena',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 27',
    front: 'What is the capital of Nebraska?',
    back: 'Lincoln',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 28',
    front: 'What is the capital of Nevada?',
    back: 'Carson City',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 29',
    front: 'What is the capital of New Hampshire?',
    back: 'Concord',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 30',
    front: 'What is the capital of New Jersey?',
    back: 'Trenton',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 31',
    front: 'What is the capital of New Mexico?',
    back: 'Santa Fe',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 32',
    front: 'What is the capital of New York?',
    back: 'Albany',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 33',
    front: 'What is the capital of North Carolina?',
    back: 'Raleigh',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 34',
    front: 'What is the capital of North Dakota?',
    back: 'Bismarck',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 35',
    front: 'What is the capital of Ohio?',
    back: 'Columbus',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 36',
    front: 'What is the capital of Oklahoma?',
    back: 'Oklahoma City',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 37',
    front: 'What is the capital of Oregon?',
    back: 'Salem',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 38',
    front: 'What is the capital of Pennsylvania?',
    back: 'Harrisburg',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 39',
    front: 'What is the capital of Rhode Island?',
    back: 'Providence',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 40',
    front: 'What is the capital of South Carolina?',
    back: 'Columbia',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 41',
    front: 'What is the capital of South Dakota?',
    back: 'Pierre',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 42',
    front: 'What is the capital of Tennessee?',
    back: 'Nashville',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 43',
    front: 'What is the capital of Texas?',
    back: 'Austin',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 44',
    front: 'What is the capital of Utah?',
    back: 'Salt Lake City',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 45',
    front: 'What is the capital of Vermont?',
    back: 'Montpelier',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 46',
    front: 'What is the capital of Washington?',
    back: 'Seattle',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 47',
    front: 'What is the capital of West Virginia?',
    back: 'Charleston',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 48',
    front: 'What is the capital of Wisconsin?',
    back: 'Madison',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
  Note(
    subject: 'Geography',
    content: 'This is the content of note 49',
    front: 'What is the capital of Wyoming?',
    back: 'Cheyenne',
    learned: false,
    tags: ['states', 'capitals'],
    fav: false,
    pinned: false,
  ),
];
